spring:
  profiles:
    active: dev
  main:
    allowBeanDefinitionOverriding: true

camel:
  springboot:
    name: int-sap
  component:
    servlet:
      mapping:
        contextPath: /api/*

management:
  server:
    port: 8081

  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

